### ISSUE TITLE
wwwroot 下的前端文件没有。

### ISSUE THREAD

**Issue by yruson** [sdcb/chats#12]
wwwroot 下的前端文件没有。

**Comment by sdcb** [comment]
您好，非常感谢您对这个项目开发和调试工作的关注和支持！🥰

该项目采取了前后端分离的结构。前端部分位于 `/src/FE` 目录下，您可以通过运行以下命令来启动前端：

```
npm i && npm run dev
```

不过，该项目也支持前后端合并。在这种模式下，Github Actions 会自动将前端进行编译并拷贝到后端的 `wwwroot` 目录中。您可以在以下代码段中查看实现细节：

[查看代码段](https://github.com/sdcb/chats/blob/153410338cb1ce1f7ab56d9da064b6a23c5a4c30/.github/workflows/build-container.yml#L110-L114)

如果您对前端开发不灵敏，因此不特别关注前端结构，也无需担心。您同样可以直接从网上下载编译好的最新前端文件，然后将其解压至 `wwwroot` 目录。下载地址如下：

- 全球访问： [下载地址](https://github.com/sdcb/chats/releases/latest/download/chats-fe.zip)
  
- 国内访问： [下载地址](https://io.starworks.cc:88/chats/latest/chats-fe.zip)

希望这能帮到您，祝您使用愉快！

**Comment by yruson** [comment]
知悉，谢谢！

**Comment by yruson** [comment]
知悉，谢谢。
