### ISSUE TITLE
添加文心一言模型后验证模型报错

### ISSUE THREAD

**Issue by caopengfei** [sdcb/chats#14]
![image](https://github.com/user-attachments/assets/fa4b4568-e1d1-4c12-949a-1c9784f06524)
控制台输出错误日志如下：
![image](https://github.com/user-attachments/assets/5e0be322-2967-427b-b32d-81c66d880b7a)

**Comment by sdcb** [comment]
fixed, deploying: https://github.com/sdcb/chats/actions/runs/12410006061
let me know if it works

**Comment by sdcb** [comment]
deployed, please test here: https://chats-dev.starworks.cc:88/login

**Comment by sdcb** [comment]
can also try with this docker image: https://hub.docker.com/layers/sdcb/chats/r226-linux-x64/images/sha256-903f2c394b0b724f21d6d0abb5502619c7038011a0f97f46728913683f027523

sdcb/chats:r226-linux-x64
